/**
 * @fileOverview This file defines a Genkit flow for generating a proactive daily financial insight.
 *
 * - `getDailyInsight`: A function that takes a financial analysis and an AI personality to generate a comment.
 * - `GetDailyInsightInput`: The input type for the `getDailyInsight` function.
 * - `GetDailyInsightOutput`: The return type for the `getDailyInsight` function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GetDailyInsightInputSchema = z.object({
  analysis: z.string().describe('A brief text analysis of the user\'s current financial situation.'),
  systemInstruction: z.string().describe('The system instruction that defines the AI personality.'),
});
export type GetDailyInsightInput = z.infer<typeof GetDailyInsightInputSchema>;

const GetDailyInsightOutputSchema = z.object({
  insight: z.string().describe('The proactive, short, and engaging daily insight generated by the AI personality.'),
});
export type GetDailyInsightOutput = z.infer<typeof GetDailyInsightOutputSchema>;

export async function getDailyInsight(input: GetDailyInsightInput): Promise<GetDailyInsightOutput> {
  return getDailyInsightFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getDailyInsightPrompt',
  input: { schema: GetDailyInsightInputSchema },
  output: { schema: GetDailyInsightOutputSchema },
  system: '{{{systemInstruction}}}',
  prompt: `You are giving a user a quick, proactive daily financial insight. 
Based on the following analysis, give a short, engaging comment (max 2 sentences) in your persona's voice.
DO NOT repeat the numbers, just the conclusion.

Analysis: {{{analysis}}}

Your Insight:`,
});

const getDailyInsightFlow = ai.defineFlow(
  {
    name: 'getDailyInsightFlow',
    inputSchema: GetDailyInsightInputSchema,
    outputSchema: GetDailyInsightOutputSchema,
  },
  async input => {
    try {
      const { output } = await prompt(input);
      return output!;
    } catch (error) {
      console.error("AI Error or Quota Exceeded in getDailyInsightFlow:", error);
      // If there's an error (like 429), return a fallback to prevent the app from crashing.
      return { insight: "O sistema de IA está sobrecarregado (Muitos acessos!). Mas seus gráficos estão funcionando. Tente novamente em 1 minuto. 🤖💤" };
    }
  }
);
