'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing financial advice based on a selected AI personality.
 *
 * - `getFinanceAdvice`: A function that takes user input and an AI personality to generate financial advice.
 * - `GetFinanceAdviceInput`: The input type for the `getFinanceAdvice` function.
 * - `GetFinanceAdviceOutput`: The return type for the `getFinanceAdvice` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetFinanceAdviceInputSchema = z.object({
  userInput: z.string().describe('The user\u2019s question or request for financial advice.'),
  aiPersonality: z
    .string()
    .describe(
      'The selected AI personality to provide the financial advice. Examples: Warren Buffett, Suze Orman, Dave Ramsey'
    ),
});
export type GetFinanceAdviceInput = z.infer<typeof GetFinanceAdviceInputSchema>;

const GetFinanceAdviceOutputSchema = z.object({
  advice: z.string().describe('The financial advice generated by the AI personality.'),
});
export type GetFinanceAdviceOutput = z.infer<typeof GetFinanceAdviceOutputSchema>;

export async function getFinanceAdvice(input: GetFinanceAdviceInput): Promise<GetFinanceAdviceOutput> {
  return getFinanceAdviceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'getFinanceAdvicePrompt',
  input: {schema: GetFinanceAdviceInputSchema},
  output: {schema: GetFinanceAdviceOutputSchema},
  prompt: `You are a financial advisor with the personality of {{{aiPersonality}}}. Please provide financial advice to the user based on the following input:\n\n{{{userInput}}}`,
});

const getFinanceAdviceFlow = ai.defineFlow(
  {
    name: 'getFinanceAdviceFlow',
    inputSchema: GetFinanceAdviceInputSchema,
    outputSchema: GetFinanceAdviceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
