'use client';

import { collection, addDoc, Firestore } from 'firebase/firestore';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';
import type { CreditCard } from '@/lib/types';

// Omit 'id' as it will be generated by Firestore
type CardData = Omit<CreditCard, 'id'>;

/**
 * Creates a new credit card document in Firestore for a specific user.
 * This operation is non-blocking.
 *
 * @param db The Firestore instance.
 * @param userId The UID of the user.
 * @param cardData The data for the new card.
 */
export function createCard(db: Firestore, userId: string, cardData: CardData) {
  if (!db || !userId) {
    console.error('Firestore instance or User ID is missing.');
    return;
  }

  const cardsRef = collection(db, 'users', userId, 'cards');

  addDoc(cardsRef, cardData).catch((serverError) => {
    const permissionError = new FirestorePermissionError({
      path: cardsRef.path,
      operation: 'create',
      requestResourceData: cardData,
    });
    errorEmitter.emit('permission-error', permissionError);
  });
}
